# Generated by Django. Add migration for StoryInsightsOption model
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryInsightsOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, help_text='نمایش در داشبورد')),
                ('key', models.CharField(max_length=32, unique=True, choices=[
                    ('impressions', 'Impressions'),
                    ('reach', 'Reach'),
                    ('likes', 'Likes'),
                    ('replies', 'Replies'),
                    ('shares', 'Shares'),
                    ('navigation_total', 'Navigation Total'),
                    ('forward', 'Forward'),
                    ('next_story', 'Next Story'),
                    ('exited', 'Exited'),
                    ('profile_activity', 'Profile Activity'),
                    ('follows', 'Follows'),
                ])),
                ('percent_of_views', models.PositiveIntegerField(default=100, help_text='درصد نسبت به ویو')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش')),
                ('enabled', models.BooleanField(default=True, help_text='فعال باشد؟')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Story Insights Option',
                'verbose_name_plural': 'Story Insights Options',
            },
        ),
    ]
