# Generated by Django 4.2.7 on 2026-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storyinsightsoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyinsightsoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
