# Generated by Cursor on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stories/thumbnails/'),
        ),
    ]

