# Generated by Django 4.2.7 on 2026-07-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_post_image',
            field=models.ImageField(blank=True, null=True, upload_to='last_post_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reach_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='highlights/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='stories.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
