# Generated by Django 4.2.7 on 2026-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_profile_last_post_image_profile_post_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='highlight',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
            preserve_default=False,
        ),
    ]
