# Generated by Django 5.2.4 on 2026-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_highlight_options_highlight_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
    ]
