# Generated by Django 4.2.7 on 2026-07-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_alter_story_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='viewcount',
            field=models.PositiveIntegerField(default=0, help_text='Number of views'),
        ),
    ]
