# Generated by Django 4.2.7 on 2026-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_story_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewvers',
            field=models.ImageField(blank=True, null=True, upload_to='last_post_images/'),
        ),
    ]
