# Generated by Django 4.2.7 on 2026-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_profile_viewvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
