# Generated by Django 4.2.7 on 2026-07-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_remove_profile_tag_storyview_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyview',
            name='tag',
        ),
        migrations.AddField(
            model_name='story',
            name='tag',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
