# Generated by Django 4.2.7 on 2026-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_remove_storyview_tag_story_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='link_clicks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='sticker_taps',
            field=models.BooleanField(default=False),
        ),
    ]
