# Generated by Django 4.2.7 on 2026-07-24 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_story_link_clicks_story_sticker_taps'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryMentionTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='story/mention-targets/')),
                ('url', models.URLField(blank=True, help_text='Optional external/profile URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Story Mention Target',
                'verbose_name_plural': 'Story Mention Targets',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='StoryInteractiveElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('link', 'Visit Link'), ('mention', 'Mention/Profile')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, help_text='Optional custom title. For link defaults to Visit Link.', max_length=80)),
                ('url', models.URLField(blank=True, help_text='Required for Visit Link type.')),
                ('position_preset', models.CharField(choices=[('custom', 'Custom'), ('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('link_button', 'Link Button Area'), ('mention_badge', 'Mention Badge Area')], default='custom', max_length=30)),
                ('x', models.DecimalField(decimal_places=2, default=25, help_text='Hitbox left position in percent. 0 to 100.', max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, default=65, help_text='Hitbox top position in percent. 0 to 100.', max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=50, help_text='Hitbox width in percent. 0 to 100.', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=10, help_text='Hitbox height in percent. 0 to 100.', max_digits=5)),
                ('popup_x', models.DecimalField(decimal_places=2, default=50, help_text='Popup center X in percent.', max_digits=5)),
                ('popup_y', models.DecimalField(decimal_places=2, default=55, help_text='Popup center Y in percent.', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mention_target', models.ForeignKey(blank=True, help_text='Required for Mention/Profile type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_elements', to='stories.storymentiontarget')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_elements', to='stories.story')),
            ],
            options={
                'verbose_name': 'Story Interactive Element',
                'verbose_name_plural': 'Story Interactive Elements',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
