# Generated by Django 4.2.7 on 2026-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_storymentiontarget_storyinteractiveelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyinteractiveelement',
            name='height',
        ),
        migrations.RemoveField(
            model_name='storyinteractiveelement',
            name='popup_x',
        ),
        migrations.RemoveField(
            model_name='storyinteractiveelement',
            name='popup_y',
        ),
        migrations.RemoveField(
            model_name='storyinteractiveelement',
            name='width',
        ),
        migrations.AlterField(
            model_name='storyinteractiveelement',
            name='position_preset',
            field=models.CharField(choices=[('custom', 'Custom'), ('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom'), ('link_button', 'Link Button Area'), ('mention_badge', 'Mention Badge Area')], default='custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='storyinteractiveelement',
            name='x',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Hitbox left position in percent. Example: 12', max_digits=5),
        ),
        migrations.AlterField(
            model_name='storyinteractiveelement',
            name='y',
            field=models.DecimalField(decimal_places=2, default=63, help_text='Hitbox top position in percent. Example: 63', max_digits=5),
        ),
    ]
