# Generated by Django 6.0.7 on 2026-07-30 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0016_remove_storyinteractiveelement_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'هایلایت', 'verbose_name_plural': 'هایلایت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at'], 'verbose_name': 'استوری', 'verbose_name_plural': 'استوری\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='storyinteractiveelement',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'عنصر تعاملی', 'verbose_name_plural': 'عناصر تعاملی'},
        ),
        migrations.AlterModelOptions(
            name='storymentiontarget',
            options={'ordering': ['username'], 'verbose_name': 'هدف منشن', 'verbose_name_plural': 'اهداف منشن'},
        ),
        migrations.AlterModelOptions(
            name='storyview',
            options={'ordering': ['-created_at'], 'verbose_name': 'استوری', 'verbose_name_plural': 'استوری\u200cها'},
        ),
        migrations.AddField(
            model_name='profile',
            name='viewvers2',
            field=models.ImageField(blank=True, null=True, upload_to='last_post_images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storyinteractiveelement',
            name='position_preset',
            field=models.CharField(choices=[('custom', 'Custom'), ('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='custom', max_length=30),
        ),
    ]
